export const words = [
    'elephant', 'giraffe', 'kangaroo', 'penguin', 'dolphin', 'octopus', 'cheetah', 'peacock', 'zebra', 'rhinoceros',
    'hedgehog', 'squirrel', 'whale', 'eagle', 'flamingo', 'turtle', 'crocodile', 'starfish', 'wolf', 'hamster',
    'rabbit', 'lion', 'tiger', 'bear', 'fox', 'bat', 'frog', 'snake', 'shark', 'chameleon', 'koala', 'owl', 'panda',
    'seal', 'antelope', 'chimpanzee', 'beaver', 'donkey', 'umbrella', 'laptop', 'airplane', 'television', 'guitar',
    'camera', 'microscope', 'robot', 'bicycle', 'motorcycle', 'toaster', 'lamp', 'fountain', 'clock', 'compass',
    'helmet', 'ladder', 'wheelchair', 'binoculars', 'backpack', 'fridge', 'washing machine', 'stethoscope', 'canoe',
    'megaphone', 'shovel', 'ruler', 'calculator', 'barbecue', 'kettle', 'roller skates', 'telescope', 'firefighter',
    'teacher', 'chef', 'doctor', 'scientist', 'pilot', 'farmer', 'artist', 'mechanic', 'architect', 'journalist',
    'carpenter', 'plumber', 'electrician', 'gardener', 'astronaut', 'veterinarian', 'dentist', 'programmer',
    'engineer', 'musician', 'nurse', 'magician', 'lawyer', 'police officer', 'mountain', 'river', 'volcano', 'ocean',
    'desert', 'waterfall', 'rainbow', 'sunset', 'island', 'forest', 'canyon', 'meadow', 'iceberg', 'prairie', 'cliff',
    'lagoon', 'glacier', 'jungle', 'tornado', 'hurricane', 'cave', 'reef', 'crater', 'valley', 'geyser', 'cloud',
    'frost', 'swimming', 'skiing', 'dancing', 'reading', 'writing', 'singing', 'hiking', 'camping', 'fishing',
    'surfing', 'cycling', 'painting', 'gardening', 'baking', 'cooking', 'skateboarding', 'jogging', 'meditating',
    'rock climbing', 'bird watching', 'playing guitar', 'photography', 'playing chess', 'happiness', 'freedom',
    'hope', 'friendship', 'peace', 'love', 'justice', 'strength', 'wisdom', 'courage', 'patience', 'ambition',
    'luck', 'kindness', 'adventure', 'imagination', 'dream', 'creativity', 'teamwork', 'truth', 'memory', 'future',
    'fear', 'trust', 'loyalty', 'mystery', 'surprise', 'sadness', 'challenge', 'faith', 'robot', 'pyramid',
    'spaceship', 'lighthouse', 'castle', 'tent', 'bridge', 'sword', 'shield', 'cannon', 'trumpet', 'violin', 'drum',
    'banjo', 'bowtie', 'necklace', 'bracelet', 'hat', 'helmet', 'glasses', 'balloon', 'kite', 'parachute', 'rocket',
    'satellite', 'submarine', 'train', 'bus', 'tractor', 'yacht', 'sailboat', 'hoverboard', 'ferris wheel',
    'roller coaster', 'pizza', 'burger', 'spaghetti', 'sushi', 'pancake', 'ice cream', 'chocolate', 'cookie',
    'cheese', 'sandwich', 'salad', 'omelet', 'noodles', 'taco', 'burrito', 'steak', 'fried chicken', 'popcorn',
    'hotdog', 'pudding', 'cake', 'pie', 'brownie', 'doughnut', 'muffin', 'waffle', 'cupcake', 'bread', 'bagel',
    'croissant', 'red', 'blue', 'yellow', 'green', 'purple', 'orange', 'pink', 'black', 'white', 'grey', 'brown',
    'turquoise', 'indigo', 'gold', 'silver', 'soccer', 'basketball', 'baseball', 'tennis', 'cricket', 'rugby',
    'hockey', 'golf', 'boxing', 'archery', 'badminton', 'karate', 'judo', 'fencing', 'swimming', 'track', 'cycling',
    'skating', 'rowing', 'kayaking', 'climbing', 'diving', 'Christmas tree', 'snowman', 'Easter egg', 'pumpkin',
    'turkey', 'fireworks', 'stocking', 'snowflake', 'sleigh', 'mistletoe', 'beach', 'surfboard', 'sunflower',
    'pineapple', 'sandcastle'
];